Updated Image documentation.
StadGent/fractal_styleguide_gent-base pull request #44
Opened 2019-06-06 09:25 UTC by mattiasberlamont

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the styleguide CHANGELOG accordingly.

2019-06-06 09:42 UTC, delrueba requested changes
Can you also add that the alt attribute is required and must be empty for purely decorative images.

There's a lot of content online about writing a good alt-text, but that might lead us too far, 
perhaps it's sufficient to reference the official WCAG Technique page: https://www.w3.org/TR/WCAG20-TECHS/H37.html

2019-06-06 09:42 UTC, delrueba commented on components/31-molecules/figure/README.md
> +The image component wraps an image in a container and adds the benefit of providing an optional caption tag.
```suggestion
The image component wraps an image in a figure and adds the benefit of providing an optional caption tag.
```

2019-06-07 07:06 UTC, hstandaert approved these changes
Might be useful to add some information about the fact that a ratio should always be provided, that we use `8:5` as a default and a placeholder image is loading or not found.

2019-06-11 07:24 UTC, mattiasberlamont commented
Should purely decorative images be wrapped in a figure?

2019-06-11 10:49 UTC, mattiasberlamont commented
@hstandaert @delrueba. After discussing this with @delrueba I think it would be better to keep the name "Figure" for this component. I updated the documentation and also added the requirements for images you mentioned. The references from the Image Gallery en Image Wall component documentation were also updated. Could you please review the changes?

2019-06-11 11:26 UTC, delrueba approved these changes
OK for me

2019-06-13 07:04 UTC, mattiasberlamont commented
@hstandaert OK for you?

2019-06-14 05:49 UTC, hstandaert approved these changes

2019-06-14 07:02 UTC, merged