Fix invalid color
StadGent/fractal_styleguide_gent-base pull request #63
Opened 2019-07-17 12:47 UTC by MPParsley

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the styleguide CHANGELOG accordingly.

2019-07-17 13:03 UTC, delrueba requested changes
These files are auto generated.

2019-07-17 13:12 UTC, delrueba commented
Issue seems to be line 543 in gulpfile.js
change the color to lowercase and run 'gulp favicon'

2019-07-17 13:28 UTC, delrueba submitted a review, later dismissed

2019-07-17 13:29 UTC, delrueba commented
You're going to need another volunteer to approve this now ;)

2019-07-29 09:35 UTC, hstandaert approved these changes

2019-07-29 11:23 UTC, merged