Feature/image
StadGent/fractal_styleguide_gent-base pull request #72
Opened 2019-08-27 08:59 UTC by hstandaert

## Description

* Removed figure component and merged it into `Image`
* Update image placeholder according to design (https://zpl.io/VxBpDpx)
* Added broken image placeholder

## Screenshots (if appropriate):
![screencapture-localhost-3000-components-preview-image-2019-08-27-10_56_43](https://user-images.githubusercontent.com/4415097/63757047-bb656480-c8b9-11e9-9a26-6a88b117cf19.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] I have updated the documentation accordingly.
- [x] I have updated the styleguide CHANGELOG accordingly.

2019-08-27 09:18 UTC, delrueba requested changes
What about the figure documentation?

2019-08-27 10:42 UTC, hstandaert commented
> What about the figure documentation?

Good point! I added it to the `Image` component. @mattiasberlamont, could you review whether this documentation is sufficient for the Image component?

2019-08-28 11:24 UTC, mattiasberlamont commented on components/21-atoms/image/README.md
> +* <a href="{{path './teaser.html'}}">Teaser component</a>
```suggestion
* <a href="{{path './header.html'}}">Header component</a>
```

2019-08-28 11:31 UTC, mattiasberlamont commented
@hstandaert I could not find how to do suggestions in a proper way, so I updated the documentation myself and added a commit.

Another suggestion based on the screenshot (but I cannot change it myself):

* I would rename the variation "placeholder" to "no image placeholder".
* I would rename the variation "broken" to "broken image placeholder".

This to make clear which placeholder should be used when.

I refer to these placeholders in the updated Image documentation.

2019-08-29 06:09 UTC, hstandaert commented
> @hstandaert I could not find how to do suggestions in a proper way, so I updated the documentation myself and added a commit.
> 
> Another suggestion based on the screenshot (but I cannot change it myself):
> 
> * I would rename the variation "placeholder" to "no image placeholder".
> * I would rename the variation "broken" to "broken image placeholder".
> 
> This to make clear which placeholder should be used when.
> 
> I refer to these placeholders in the updated Image documentation.

@mattiasberlamont, thanks for you contribution. I have updated the naming of the variants as suggested 🙂

2019-08-29 10:44 UTC, delrueba approved these changes

2019-08-29 10:44 UTC, merged